[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
fs_permissions = [
    { access = "read", path = "./config" },
    { access = "read-write", path = "./deployments" },
]
remappings = [
    "@chainlink/local/=lib/chainlink-local/",
    "@chainlink/contracts/=lib/chainlink-local/lib/chainlink-evm/contracts/",
    "@chainlink/contracts-ccip/=lib/chainlink-local/lib/chainlink-ccip/chains/evm/",
    "@openzeppelin/contracts@5.0.2/=lib/chainlink-local/src/vendor/openzeppelin-solidity/v5.0.2/contracts/",
]

[rpc_endpoints]
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[etherscan]
ethereum_sepolia = { key = "${ETHERSCAN_API_KEY}", chain = 11155111 }
base_sepolia = { key = "${BASESCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
